name: Auto approver
on:
  pull_request_review_comment:
    types: [created]

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - name: generate GitHub Apps token
        id: generate-github-apps
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.BOT_APP_ID }}
          private_key: ${{ secrets.BOT_PRIVATE_KEY }}
