name: Create release PR
on:
  workflow_dispatch:
    inputs:
      pr-title-suffix:
        description: タイトルの接尾辞
        required: false

jobs:
  create-release-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
      - run: gem install git-pr-release
      - run: git-pr-release --dry-run --json
        id: create-release-pr
        env:
          GIT_PR_RELEASE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_PR_RELEASE_BRANCH_PRODUCTION: main
          GIT_PR_RELEASE_BRANCH_STAGING: develop
          GIT_PR_RELEASE_TEMPLATE: .github/workflows/release-pr-template.erb
          TZ: Asia/Tokyo
          RELEASE_PR_TITLE_SUFFIX: ${{ github.event.inputs.pr-title-suffix }}
      - run: echo "${{ steps.create-release-pr.outputs }}"
