name: Create release PR
on:
  workflow_dispatch:
    inputs:
      pr-title-suffix:
        description: PR タイトルの接尾辞
        required: false

jobs:
  create-release-pr:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
      - uses: bakunyo/git-pr-release-action@v1.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_PR_RELEASE_BRANCH_PRODUCTION: main
          GIT_PR_RELEASE_BRANCH_STAGING: develop
          GIT_PR_RELEASE_TEMPLATE: |-
            Release <%= Time.now %> ${{ github.event.inputs.pr-title-suffix }}
            <% pull_requests.each do |pr| -%>
            <%= "- #" + pr.number %>
            <% end -%>
          TZ: Asia/Tokyo
