name: Create release PR
on:
  workflow_dispatch:
    inputs:
      pr-title-suffix:
        description: タイトルの接尾辞
        required: false

jobs:
  create-release-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
      - run: gem install git-pr-release
      - name: Create release PR
        id: create-release-pr
        run: echo "::set-output name=created-pr-and-marged-prs::$(git-pr-release --dry-run --json | tail -n 1)"
        env:
          GIT_PR_RELEASE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_PR_RELEASE_BRANCH_PRODUCTION: main
          GIT_PR_RELEASE_BRANCH_STAGING: develop
          GIT_PR_RELEASE_TEMPLATE: .github/workflows/release-pr-template.erb
          TZ: Asia/Tokyo
          RELEASE_PR_TITLE_SUFFIX: ${{ github.event.inputs.pr-title-suffix }}
      - name: Extract marged PR's titles
        id: extract-merged-prs-titles
        uses: actions/github-script@v6
        with:
          script: |
            let margedPRs = JSON.parse('${{ steps.create-release-pr.outputs.created-pr-and-marged-prs }}').marged_pull_requests;
            return margedPRs.map(margedPR => `- ${margedPR.data.title}`).join('\\n');
          result-encoding: string
      - run: echo "${{ steps.extract-merged-prs-titles.outputs.result }}"
