name: Print when an issuer is created

on:
  workflow_dispatch:

jobs:
  print:
    runs-on: ubuntu-20.04
    steps:
      - run: |
          echo "${{ github.event.issue.title }} #${{ github.event.issue.number }} ${{ github.event.issue.html_url }}"
