name: Mask test
on:
  workflow_dispatch:
    inputs:
      WEBHOOK_TOKEN:
        description: should mask!
        required: true

jobs:
  mask-test:
    runs-on: ubuntu-latest
    steps:
      - run: echo $WEBHOOK_TOKEN
        env:
          WEBHOOK_TOKEN: ${{ github.event.inputs.WEBHOOK_TOKEN }}
